# Generated by Django 5.1.6 on 2025-02-11 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clases', '0003_remove_clase_formularios_delete_formulario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('formulario', models.FileField(upload_to='formularios/')),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clases.clase')),
            ],
        ),
    ]
