# Generated by Django 5.1.6 on 2025-02-11 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clase',
            name='examenes',
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('formulario', models.FileField(upload_to='formularios/')),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clases.clase')),
            ],
        ),
        migrations.AddField(
            model_name='clase',
            name='formularios',
            field=models.ManyToManyField(related_name='formularios', to='clases.formulario'),
        ),
    ]
