# Generated by Django 5.1.6 on 2025-02-11 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0002_remove_clase_examenes_formulario_clase_formularios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clase',
            name='formularios',
        ),
        migrations.DeleteModel(
            name='Formulario',
        ),
    ]
