# Generated by Django 5.1.6 on 2025-02-11 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='correo',
            field=models.EmailField(default='no-email@default.com', max_length=254),
        ),
        migrations.AddField(
            model_name='alumno',
            name='matricula',
            field=models.CharField(default='no-email@default.com', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumno',
            name='nombre',
            field=models.CharField(default='no-email@default.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maestro',
            name='correo',
            field=models.EmailField(default='no-email@default.com', max_length=254),
        ),
        migrations.AddField(
            model_name='maestro',
            name='nombre',
            field=models.CharField(default='no-email@default.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maestro',
            name='numero_cuenta',
            field=models.CharField(default='defaultuser@domain.com', max_length=10),
            preserve_default=False,
        ),
    ]
