# Generated by Django 5.1.6 on 2025-02-12 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alumno_correo_alumno_matricula_alumno_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='maestro',
            name='usuario',
        ),
    ]
