# Generated by Django 5.1.6 on 2025-02-12 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_alumno_usuario_remove_maestro_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='contrasena',
            field=models.CharField(default='contraseña123', max_length=100),
        ),
        migrations.AddField(
            model_name='maestro',
            name='contrasena',
            field=models.CharField(default='contraseña123', max_length=100),
        ),
    ]
